// <auto-generated />
using EvaluacionFinalMitocode_backend.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvaluacionFinalMitocode_backend.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("ClienteSeq", "Users");

            modelBuilder.Entity("EvaluacionFinalMitocode_backend.Entities.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasDefaultValueSql("'CLT' + RIGHT(REPLICATE('0', 4) + CAST(NEXT VALUE FOR [Users].[ClienteSeq] AS VARCHAR(10)), 4)");

                    b.Property<bool>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_DNI");

                    b.HasIndex("Apellidos", "Nombres")
                        .HasDatabaseName("IX_Cliente_Apellidos_Nombres");

                    b.ToTable("Clientes", "Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Clientes_DNI", "LEN([DNI]) = 8 AND [DNI] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_Users_Clientes_Edad", "[Edad] BETWEEN 0 AND 120");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
